name: apply

on: 
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
        
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      selected-stage: ${{ steps.selected-environment.outputs.selected-stage }}
    steps:
    - name: select environment
      id: select-environment
      run: |
        if [ ${{ inputs.target-env }} == dev ]; then
          echo "selected-stage=dev" >>  "$GITHUB_OUTPUT"
        elif [ ${{ inputs.target-env }} == dev ]; then
          echo "selected-stage=stage" >>  "$GITHUB_OUTPUT"
        elif [ ${{ inputs.target-env }} == dev ]; then
          echo "selected-stage=prod" >>  "$GITHUB_OUTPUT"
        else
          echo " select a valid environment"
        fi
  deploy-dev:
    needs: check
    if: ${{ needs.check.outputs.selected == 'dev' }}
    uses: gabrielehima/shared-workflows/.github/workflows/apply.yml@main

  deploy-stage:
    needs: check
    if: ${{ needs.check.outputs.selected == 'stage' }}
    uses: gabrielehima/shared-workflows/.github/workflows/apply.yml@main
      
  deploy-prod:
    needs: check
    if: ${{ needs.check.outputs.selected == 'prod' }}
    uses: gabrielehima/shared-workflows/.github/workflows/apply.yml@main
        
