name: build workflow
on:
  - push
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"
  startup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello" 
  setup:
    needs: [ build, docker, startup ]
    uses: gabrielehima/shared-workflows/.github/workflows/setup.yml@main
  checkov:
    needs: setup
    uses: gabrielehima/shared-workflows/.github/workflows/tests.yml@main
  plan:
    needs: checkov
    if: success()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envi: [ dev, stage, prod ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test.tf
      - run: terraform init
  apply:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envi: [ dev, stage, prod ]
    steps:
      - run: echo ${{ matrix.envi }}
  docker:
    runs-on: ubuntu-latest
    steps:
        - run: echo "hello"
  trivy:
    needs: [ docker, setup ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  dockerise: 
    needs: trivy
    if: success()
    runs-on: ubuntu-latest
    steps: 
     - run: echo "hello"
