on:
  - push
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"
  setup:
    needs: [build, docker]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  checkov:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echoo "hello"
  plan:
    needs: checkov
    if: success()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envi: [ dev, stage, prod ]
    steps:
      - run: echo ${{ matrix.envi }}
  apply:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envi: [ dev, stage, prod ]
    steps:
      - run: echo ${{ matrix.envi }}
  docker:
    runs-on: ubuntu-latest
    steps:
        - run: echo "hello"
  trivy:
    needs: [ docker, setup ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  dockerise: 
    needs: trivy
    if: success()
    runs-on: ubuntu-latest
    steps: 
     - run: echo "hello"
