on:
  - push
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"
  setup:
    needs: [build, docker]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  checkov:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  plan:
    needs: checkov
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  apply:
      needs: plan
      runs-on: ubuntu-latest
      steps:
        - run: echo "hello"
  docker:
    runs-on: ubuntu-latest
    steps:
        - run: echo "hello"
  trivy:
    needs: [ docker, setup ]
    runs-on: ubuntu-lastest
    steps:
      - run: echo "hello"
  dockerise: 
    needs: trivy 
    runs-on: ubuntu-latest
    steps: 
     - run: echo "hello"
